source 'https://rubygems.org'

gem 'rails', '~> 4.0.0'
gem 'american_date'
gem 'activerecord-session_store'
gem 'devise'
gem 'formtastic', '~>2.3.0'
gem 'responders'
gem 'inherited_resources'
gem 'ransack'
gem 'activeadmin', github: 'gregbell/active_admin', branch: 'master'
gem 'kaminari'
gem 'capistrano', '~> 2.15'
gem 'capistrano-ext'
gem 'pg'
gem 'paperclip', '~> 3.5.4'
gem 'aws-sdk'
gem 'httparty'
gem 'jquery-rails', '3.0.0'
gem 'jquery-ui-rails'
gem 'jquery-ui-sass-rails'
gem 'haml'
gem 'foreigner'
gem 'active_pdftk', git: 'https://github.com/tcocca/active_pdftk.git'
gem 'nokogiri'
gem 'sass-rails'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails'
gem 'compass-rails', '~> 1.1.7'
gem 'bootstrap-sass', '~> 2.3.2.0'
gem 'angularjs-rails'
gem 'sprockets-rails', require: 'sprockets/railtie'
gem 'airbrake'
gem 'jbuilder'
gem 'yajl-ruby'
gem 'request_exception_handler'
gem 'validates_email_format_of'
gem 'cancancan'
gem 'ruby-filemagic'
gem 'geocoder'
gem 'rubyzip'
gem 'savon', '~> 2.0'
gem 'whenever', require: false
gem 'roo'
gem 'ckeditor'
gem 'non-stupid-digest-assets'
gem 'active_model_serializers', '~> 0.8.0' # 0.10.x will be based on the 0.8.0 code, but with a more flexible architecture. try upgrading to 0.10.0 when available
gem 'chartkick'
gem 'groupdate'
gem 'rollbar'
gem 'enumerize'
gem 'sidekiq'
gem 'capistrano-sidekiq', group: :development
gem 'sinatra', require: false
gem 'activerecord-import'

group :production, :staging do
  gem 'newrelic_rpm'
end

group :test do
  gem 'rspec', '~> 3.1.0'
  gem 'rspec-rails', '~> 3.1.0'
  gem 'cucumber-rails', require: false
  gem 'simplecov'
  gem 'email_spec'
  gem 'json_spec', github: 'collectiveidea/json_spec'
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'database_cleaner', '~>1.3.0'
  gem 'poltergeist', '~> 1.5', require: false
  gem 'webmock'
  gem 'vcr'
  gem 'factory_girl_rails'
  gem 'codeclimate-test-reporter', require: false
  gem 'coveralls', require: false
  # gem 'cucumber-rails', require: false, github: 'cucumber/cucumber-rails',  branch: 'master_rails4_test'
  # gem 'ci_reporter'
end

group :development do
  gem 'awesome_print'
  gem 'bullet'
  gem 'passenger', '~> 4.0.0'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'meta_request'
  gem 'guard'
  gem 'guard-rails'
  gem 'guard-migrate'
  gem 'guard-cucumber'
  gem 'guard-livereload'
  gem 'guard-rspec'
  gem 'railroady'
  gem 'letter_opener'
  gem 'yard'
  gem 'yard-activerecord'
  gem 'quiet_assets'
  gem 'thin'
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'guard-spring'
  # gem 'localtunnel'
  # gem 'pickler', github: 'domain7/pickler'
end

group :test, :development do
  gem 'byebug'
  gem 'faker'
  gem 'pry'
  gem 'pry-debugger'
  gem 'pry-stack_explorer'
  gem 'parallel_tests'
end
